functional:
  - У пользователя должна быть возможность зарегистрироваться через GitHub
  - У пользователя должна быть возможность играть против бота, случайного соперника или друга по ссылке
  - У пользователя должна быть возможность выбрать язык программирования для решения задачи
  - У пользователя должна быть возможность писать код в редакторе с подсветкой синтаксиса
  - У пользователя должна быть возможность запустить тесты для проверки своего решения
  - У пользователя должна быть возможность видеть прогресс решения соперника
  - У пользователя должна быть возможность общаться с соперником в чате во время игры
  - У пользователя должна быть возможность просматривать свой рейтинг и статистику
  - У пользователя должна быть возможность просматривать историю сыгранных игр
  - У пользователя должна быть возможность переподключиться к игре при разрыве соединения
  - У победившего пользователя должна блокироваться кнопка проверки решения
  - У проигравшего пользователя должна сохраняться возможность писать код после завершения игры
  - Игра должна завершаться только после выхода обоих игроков

non-functional:
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть безопасным (аутентификация через GitHub OAuth, защита данных пользователя)
  - Сайт должен быть способен обрабатывать активное использование (не падает при одновременной игре 2+ пользователей)
  - Страницы сайта должны загружаться за 3-5 секунд
  - Редактор кода должен работать без задержек при вводе
  - Данные об игре должны храниться до полного завершения сессии (выхода обоих игроков)
  - Система должна поддерживать синхронизацию кода в реальном времени (через WebSocket или аналогичную технологию)
  - Система должна поддерживать восстановление игровой сессии по её идентификатору
  - Игра не должна прерываться по таймеру — только по решению задачи или выходу игроков

implicit:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  
